/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prototipotres.gui;

import com.mycompany.prototipotres.servicios.ServicioDueñoContacto;
import com.mycompany.prototipotres.servicios.ServicioMascota;
import com.mycompany.prototipotres.servicios.ServicioVeterinaria;
import javax.swing.JOptionPane;

/**
 *
 * @author pauda
 */
public class GUIMigrarDatos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIMigrarDatos.class.getName());

    /**
     * Creates new form GUIMigrarDatos
     */
    public GUIMigrarDatos() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRegistrosAct = new javax.swing.JTextField();
        btnMigrar = new javax.swing.JButton();
        btnContarRegistros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GUI_Principal");

        jLabel1.setText("Registros actuales:");

        btnMigrar.setText("Migrar Datos");
        btnMigrar.addActionListener(this::btnMigrarActionPerformed);

        btnContarRegistros.setText("Contar Registros");
        btnContarRegistros.addActionListener(this::btnContarRegistrosActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRegistrosAct, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnContarRegistros))
                    .addComponent(btnMigrar))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRegistrosAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContarRegistros))
                .addGap(18, 18, 18)
                .addComponent(btnMigrar)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMigrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMigrarActionPerformed
        
        boolean respuesta1 = ServicioVeterinaria.migrarVeterinarias();
        boolean respuesta2 = ServicioMascota.migrarMascotas();
        boolean respuesta3 = ServicioDueñoContacto.migrarDuenoContacto();
        
        if (respuesta1 && respuesta2 && respuesta3){
            boolean res = true;
            
            if (res){
                JOptionPane.showInternalMessageDialog(null, "Registros migrados exitosamente");
            }else{
                JOptionPane.showInternalMessageDialog(null, "Error al migrar datos");
            }
        }
        
    }//GEN-LAST:event_btnMigrarActionPerformed

    private void btnContarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarRegistrosActionPerformed
        
        int regVet = ServicioVeterinaria.contarRegistros();
        int regMas = ServicioMascota.contarRegistros();
        int regDuenosCont = ServicioDueñoContacto.contarRegistros();
        
        int total_registros = regVet + regMas + regDuenosCont;
        
        txtRegistrosAct.setText(String.valueOf(total_registros));
        
    }//GEN-LAST:event_btnContarRegistrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIMigrarDatos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContarRegistros;
    private javax.swing.JButton btnMigrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtRegistrosAct;
    // End of variables declaration//GEN-END:variables
}
